#!/usr/bin/env bash

## Copyright (C) 2020-2021 Fabrice Corraire <antidote1911@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Openbox Pipemenu commands for somes gadgets

# Variables and functions
MENUS_LIBDIR='/usr/share/packarch/openbox/menulib'
if ! . "$MENUS_LIBDIR/packarch.cfg" 2> /dev/null; then
	echo "Error: Failed to locate packarch.cfg in $MENUS_LIBDIR" >&2
	exit 1
fi

menuStart
	menuItem 'Lecteur Musique Ncurse' "alacritty -e ncmpcpp"
	menuItem 'Visualiseur Audio' "alacritty -e cava"
	menuItem 'Infos Neofetch' "alacritty -e $SHELL -c neofetch;$SHELL"
	menuItem 'Pipes Animation' "alacritty -e pipes"
	menuItem 'Matrix Vert' "alacritty -e unimatrix -n -s 96 -l o"
	menuItem 'Matrix Jaune' "alacritty -e unimatrix -n -c yellow -s 90 -l o"
	menuItem 'Matrix Bleu' "alacritty -e unimatrix -n -c blue -s 90 -l o"
	menuItem 'Matrix Rouge' "alacritty -e unimatrix -n -c red -s 90 -l o"
	menuItem 'Matrix Packarch' "alacritty -e unimatrix -c yellow -u 'Packarch'"
	
menuEnd

exit 0
