#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Commands Executed By Openbox Powermenu

## Rofi #############################################
DIR="$HOME/.config/openbox/rofi/dialogs"
MSG="Options  -  oui / o / non / n"

cdialog () {
rofi -dmenu\
    -i\
    -no-fixed-num-lines\
    -p "Etes vous sûr ? : "\
    -theme "$DIR"/confirm.rasi
}

## Options #############################################
if  [[ $1 = "--logout" ]]; then
	ans=$(cdialog)
	if [[ $ans == "oui" ]] || [[ $ans == "OUI" ]] || [[ $ans == "o" ]]; then
        openbox --exit
	elif [[ $ans == "non" ]] || [[ $ans == "NON" ]] || [[ $ans == "n" ]]; then
        exit
    else
        rofi -theme "$DIR"/askpass.rasi -e "$MSG"
    fi

elif  [[ $1 = "--suspent" ]]; then
	ans=$(cdialog)
	if [[ $ans == "oui" ]] || [[ $ans == "OUI" ]] || [[ $ans == "o" ]]; then
		mpc -q pause
		amixer set Master mute
		betterlockscreen --suspend
	elif [[ $ans == "non" ]] || [[ $ans == "NON" ]] || [[ $ans == "n" ]]; then
		exit
    else
		rofi -theme "$DIR"/askpass.rasi -e "$MSG"
    fi

elif  [[ $1 = "--reboot" ]]; then
	ans=$(cdialog)
	if [[ $ans == "oui" ]] || [[ $ans == "OUI" ]] || [[ $ans == "o" ]]; then
        systemctl reboot
	elif [[ $ans == "non" ]] || [[ $ans == "NON" ]] || [[ $ans == "n" ]]; then
        exit
    else
        rofi -theme "$DIR"/askpass.rasi -e "$MSG"
    fi

elif  [[ $1 = "--shutdown" ]]; then
	ans=$(cdialog)
	if [[ $ans == "oui" ]] || [[ $ans == "OUI" ]] || [[ $ans == "o" ]]; then
        systemctl poweroff
	elif [[ $ans == "non" ]] || [[ $ans == "NON" ]] || [[ $ans == "n" ]]; then
        exit
    else
        rofi -theme "$DIR"/askpass.rasi -e "$MSG"
    fi

## Help Menu #############################################
else
echo "
Powermenu For Openbox Menu
Developed By - Aditya Shakya (@adi1090x)

Available options:
--logout	--suspent	--reboot	--shutdown
"
fi
